using System;
using System.Collections.Generic;
using System.Text;

namespace _360Training.TrackingServiceDataLogic.Common
{
    public class StoredProcedures
    {
        public static readonly string INSERT_SEQUENCENO = "LMS_INSERT_SEQUENCENO";
        public static readonly string SELECT_SEQUENCENO = "LMS_SELECT_SEQUENCENO";
        public static readonly string UPDATE_LEARNINGSESSION_ENDTIME = "LMS_UPDATE_LEARNINGSESSION_ENDTIME_NEW";
        public static readonly string UPDATE_LEARNINGSESSION_ENDTIME_LEGACY = "LMS_UPDATE_LEARNINGSESSION_ENDTIME_LEGACY";
        public static readonly string UPDATE_LEARNINGSESSION_ENDTIME_LEGACY_ICP = "LMS_UPDATE_LEARNINGSESSION_ENDTIME_LEGACY_ICP_NEW";
        public static readonly string UPDATE_LEARNINGSESSION_ENDTIME_LEGACY_SCORM = "LMS_UPDATE_LEARNINGSESSION_ENDTIME_LEGACY_SCORM";
        public static readonly string UPDATE_LEARNINGSESSION_ENDTIME_LEGACY_TESTING = "LMS_UPDATE_LEARNINGSESSION_ENDTIME_LEGACY_TESTING_NEW";
        public static readonly string INSERT_LEARNERSTATISTICS = "LMS_INSERT_LEARNERSTATISTICS";
        public static readonly string INSERT_ICP4_LEARNERSTATISTICS = "LMS_INSERT_ICP4_LEARNERSTATISTICS";
        public static readonly string INSERT_ICP4_SAVEASSESSMENTSCORE = "INSERT_ICP4_SAVEASSESSMENTSCORE";
        public static readonly string INSERT_ICP4_SAVEASSESSMENTSCORE_GAME = "INSERT_ICP4_SAVEASSESSMENTSCORE_GAME";
        public static readonly string INSERT_ICP4_SAVEASSESSMENTITEM = "INSERT_ICP4_SAVEASSESSMENTITEM";
        public static readonly string LMS_INSERT_ICP4_LEARNERSTATISTICS_SCENE = "LMS_INSERT_ICP4_LEARNERSTATISTICS_SCENE";
        public static readonly string SELECT_LEARNERCOURSETRACKEINFO = "LMS_SELECT_LEARNERCOURSETRACKEINFO_NEW";
        public static readonly string ICP_INSERT_SETUPENROLLMENT = "ICP_INSERT_SETUPENROLLMENT";
        public static readonly string INSERT_LEARNERCOURSEBOOKMARK = "ICP_INSERT_LEARNERCOURSEBOOKMARK";
        public static readonly string SELECT_LEARNERCOURSEBOOKMARK = "ICP_SELECT_LEARNERCOURSEBOOKMARK";
        public static readonly string SELECT_LEARNERCOURSEBOOKMARKS = "ICP_SELECT_LEARNERCOURSEBOOKMARKS";
        public static readonly string SELECT_ALL_LEARNERCOURSETRACKINFO = "LMS_SELECT_ALL_LEARNERCOURSETRACKINFO_NEW";
        public static readonly string SELECT_LEARNERSTATISTICS_ASSESSMENTS = "LMS_SELECT_LEARNERSTATISTICS_ASSESSMENTS_NEW";
        public static readonly string LMS_SELECT_LEARNERSTATISTICS_QUIZASSESSMENTS_NEW = "LMS_SELECT_LEARNERSTATISTICS_QUIZASSESSMENTS_NEW";
        public static readonly string SELECT_LEARNERSTATISTICS_PREASSESSMENTATTEMPTNO = "LMS_SELECT_LEARNERSTATISTICS_PREASSESSMENTATTEMPTNO";
        public static readonly string SELECT_LEARNERSTATISTICS_POSTASSESSMENTATTEMPTNO = "LMS_SELECT_LEARNERSTATISTICS_POSTASSESSMENTATTEMPTNO";
        public static readonly string SELECT_CURRENT_LEARNERCOURSETRACKINFO = "LMS_SELECT_CURRENT_LEARNERCOURSETRACKINFO";
        public static readonly string SELECT_LEARNERSTATISTICS_PREASSESSMENTRESULT = "LMS_SELECT_LEARNERSTATISTICS_PREASSESSMENTRESULT";
        public static readonly string LMS_SELECT_LEARNERSTATISTICS_PREPOSTASSESSMENTRESULT_OPTIMIZED = "LMS_SELECT_LEARNERSTATISTICS_PREPOSTASSESSMENTRESULT_OPTIMIZED_NEW";
        public static readonly string SELECT_LEARNERSTATISTICS_POSTASSESSMENTRESULT = "LMS_SELECT_LEARNERSTATISTICS_POSTASSESSMENTRESULT";
        public static readonly string SELECT_LEARNERSTATISTICS_QUIZRESULT = "LMS_SELECT_LEARNERSTATISTICS_QUIZRESULT";
        public static readonly string LMS_SELECT_LEARNERSTATISTICS_QUIZRESULT_OPTIMIZED = "LMS_SELECT_LEARNERSTATISTICS_QUIZRESULT_OPTIMIZED_NEW";
        public static readonly string SELECT_LEARNERSTATISTICS_QUIZATTEMPTNO = "LMS_SELECT_LEARNERSTATISTICS_QUIZATTEMPTNO";
        public static readonly string INSERT_LEARNERSTATISTICSANSWER = "LMS_INSERT_LEARNERSTATISTICSANSWER";
        public static readonly string SELECT_LOCKEDCOURSE_COURSELOCKED = "LMS_SELECT_LOCKEDCOURSE_COURSELOCKED";
        public static readonly string INSERT_LOCKEDCOURSE = "LMS_INSERT_LOCKEDCOURSE";
        public static readonly string INSERT_LOCKEDCOURSEDURINGASSESSMENT = "INSERT_LOCKEDCOURSEDURINGASSESSMENT";
        public static readonly string UPDATE_LOCKEDCOURSEDURINGASSESSMENT = "UPDATE_LOCKEDCOURSEDURINGASSESSMENT";

        public static readonly string UPDATE_LEARNERSTATISTICS_MAXATTEMPTREACHACTIONTF = "LMS_UPDATE_LEARNERSTATISTICS_MAXATTEMPTREACHACTIONTF";
        public static readonly string SELECT_COURSE_COURSECOMPLETIONCONFIGURATION = "LMS_SELECT_COURSE_COURSECOMPLETIONCONFIGURATION";
        public static readonly string SELECT_LEARNERSTATISTICS_COURSECOMPLETIONDATA = "LMS_SELECT_LEARNERSTATISTICS_COURSECOMPLETIONDATA";
        public static readonly string SELECT_LEARNERSTATISTICS_COURSECOMPLETIONDATA_OPTIMIZED = "LMS_SELECT_LEARNERSTATISTICS_COURSECOMPLETIONDATA_OPTIMIZED";
        public static readonly string LMS_SELECT_LEARNERSTATISTICS_COURSECOMPLETIONDATA_OPTIMIZED_NEW = "LMS_SELECT_LEARNERSTATISTICS_COURSECOMPLETIONDATA_OPTIMIZED_NEW";
        public static readonly string ICP4_UPDATECOURSECOMPLETION = "ICP4_UPDATECOURSECOMPLETION";
        public static readonly string INSERT_LEARNINGSESSION = "LMS_INSERT_LEARNINGSESSION";
        public static readonly string SELECT_SOURCE = "LMS_SELECT_SOURCE";
        public static readonly string SELECT_LEARNINGSESSION_BRANDCODE_VARIANT = "LMS_SELECT_LEARNINGSESSION_BRANDCODE_VARIANT";
        public static readonly string ICP_SELECT_ENROLLMENTID_BRANDCODE_VARIANT = "ICP_SELECT_ENROLLMENTID_BRANDCODE_VARIANT";
        public static readonly string INSERT_LEARNERVALIDATIONSTATISTICS = "LMS_INSERT_LEARNERVALIDATIONSTATISTICS";
        public static readonly string SELECT_COURSETYPE = "LMS_SELECT_COURSETYPE";
        public static readonly string SELECT_INFOFORLMSVUCONNECTOR = "LMS_SELECT_INFOFORLMSVUCONNECTOR";
        public static readonly string UPDATE_LEARNERVALIDATIONSTATISTICS_ANSWER = "LMS_UPDATE_LEARNERVALIDATIONSTATISTICS_ANSWER";
        public static readonly string GET_LEARNING_SESSION_ID = "GET_LEARNING_SESSION_ID";
        public static readonly string LMS_GET_LEARNINGSESSION_ID_STR = "LMS_GET_LEARNINGSESSION_ID_STR";
        public static readonly string SELECT_LEARNERENROLLMENT_VALIDATIONSTATISTICS = "LMS_SELECT_LEARNERENROLLMENT_VALIDATIONSTATISTICS";
        public static readonly string GET_LEARNERPROFILE = "GET_LEARNERPROFILE";
        public static readonly string UPDATE_LEARNERPROFILE = "UPDATE_LEARNERPROFILE";
        public static readonly string UPDATE_COMPLETED_LEARNERPROFILE = "UPDATE_COMPLETED_LEARNERPROFILE";
        public static readonly string UNLOCK_LOCKEDCOURSE = "UNLOCK_LOCKEDCOURSE";
        public static readonly string GET_LEARNERCREDENTIAL = "GET_LEARNERCREDENTIAL";
        public static readonly string SELECT_LEARNERENROLLMENT_TIMESINCELASTVALIDATIONQUESTION = "LMS_SELECT_LEARNERENROLLMENT_TIMESINCELASTVALIDATIONQUESTION";
        public static readonly string DELETE_LOCKEDCOURSE = "LMS_DELETE_LOCKEDCOURSE";
        public static readonly string UPDATE_LOCKEDCOURSE = "LMS_UPDATE_LOCKEDCOURSE";
        public static readonly string SELECT_LEARNINGSESSION_RESOURCEKEY_RESOURCEVALUE = "LMS_SELECT_LEARNINGSESSION_RESOURCEKEY_RESOURCEVALUE";
        public static readonly string SELECT_RESOURCEKEY_RESOURCEVALUE = "LMS_SELECT_RESOURCEKEY_RESOURCEVALUE";
        public static readonly string SELECT_PREVIOUS_LEARNERSTATISTICS = "LMS_SELECT_PREVIOUS_LEARNERSTATISTICS";
        public static readonly string SELECT_LEARNINGSESSION_REDIRECTURL = "LMS_SELECT_LEARNINGSESSION_REDIRECTURL";
        public static readonly string SELECT_LEARNERCOURSESTATISTICS_COMPLETED = "LMS_SELECT_LEARNERCOURSESTATISTICS_COMPLETED";
        public static readonly string ICP_SELECT_DOCUSIGNSTATUS = "ICP_SELECT_DOCUSIGNSTATUS";
        public static readonly string SELECT_COURSE_CERTIFICATE_INFO = "ICP_SELECT_COURSE_CERTIFICATE_INFO";
        public static readonly string GET_LEARNER_TIMESPENT = "LMS_GET_LEARNER_TIMESPENT";
        public static readonly string LMS_GET_LEARNER_TIMESPENT_BY_TIME = "LMS_GET_LEARNER_TIMESPENT_BY_TIME";
        public static readonly string INSERT_SURVEYRESULT = "LMS_INSERT_SURVEYRESULT";
        public static readonly string INSERT_SURVEYRESULTANSWER = "LMS_INSERT_SURVEYRESULTANSWER";
        public static readonly string SELECT_COURSEEVALUATIONRESULT_ID = "LMS_SELECT_COURSEEVALUATIONRESULT_ID";
        public static readonly string LCMS_CONNECTOR_STATS_FORSCORM = "LCMS_CONNECTOR_STATS_FORSCORM";
        public static readonly string LCMS_CONNECTOR_STATS_FORICP3 = "LCMS_CONNECTOR_STATS_FORICP3";
        public static readonly string LCMS_CONNECTOR_STATS_FORICP2 = "LCMS_CONNECTOR_STATS_FORICP2";
        public static readonly string LCMS_CONNECTOR_STATS_FORCERTIFICATE = "LCMS_CONNECTOR_STATS_CERTIFICATE";
        public static readonly string UPDATE_LCMS_STUDENTCOURSE = "UPDATE_LCMS_STUDENTCOURSE";
        public static readonly string LCMS_CONNECTOR_STATS_FORTESTING = "LCMS_CONNECTOR_STATS_FORTESTING";
        public static readonly string ICP_UPDATE_LEARNERCOURSESTATISTICS = "ICP_UPDATE_LEARNERCOURSESTATISTICS";
        public static readonly string ICP_AUTHENTICATEPROCTOR = "ICP_AUTHENTICATEPROCTOR"; // LMC-9455
        public static readonly string ICP_AUTHENTICATESPECIALPOSTASSESMENTVALIDATION = "ICP_AUTHENTICATESPECIALPOSTASSESMENTVALIDATION";
        public static readonly string ICP_CHECKFORPROCTORLOGINREQUIREMENT = "ICP_CHECKFORPROCTORLOGINREQUIREMENT"; // LMC-9455
        public static readonly string ICP_AUTHENTICATENYINSURANCEVALIDATION = "ICP_AUTHENTICATENYINSURANCEVALIDATION";
        public static readonly string UPDATE_ICP4_ASSESSMENTITEM_RESETBYATTEMPT = "UPDATE_ICP4_ASSESSMENTITEM_RESETBYATTEMPT";//LCMS-10266
        //Abdus Samad 
        //LCMS-11888
        //START
        public static readonly string GET_ASSET = "GET_ASSET";
        public static readonly string GET_COURSEAPPROVALAFFIDAVIT = "ICP_SELECT_COURSEAPPROVALAFFIDAVIT";
        //STOP
        
        //LCMS-10877
        public static readonly string INSERT_COURSE_RATING = "INSERT_COURSE_RATING";
        public static readonly string INSERT_COURSE_RATINGNPS = "INSERT_COURSE_RATINGNPS";
        public static readonly string GET_COURSE_RATING_COUNT2 = "GET_COURSE_RATING_COUNT2";
        public static readonly string GET_COURSE_USER_RATINGNPS = "GET_COURSE_USER_RATINGNPS";
        public static readonly string GET_COURSE_USER_RATING = "GET_COURSE_USER_RATING";

        //LCMS-12532 Yasin
        public static readonly string INSERT_VALIDATION_IDENTITY_QUESTIONS_ANSWERS = "INSERT_VALIDATION_IDENTITY_QUESTIONS_ANSWERS";
        public static readonly string CHECK_ISVALIDATIONQUESTION_ASKEDBEFORE = "CHECK_ISVALIDATIONQUESTION_ASKEDBEFORE";

        //Abdus SAMAD 
        //LCMS-11974
        //START
        public static readonly string GET_LEARNERPROFILEINFORMATION = "GET_LEARNERPROFILEINFORMATION";
        //STOP

        //Abdus Samad
        //lcms-12502
        //Start
        public static readonly string INSERT_ICP4_DOCUSIGNROLEAGAINSTLEARNERENROLLMENT = "INSERT_ICP4_DOCUSIGNROLEAGAINSTLEARNERENROLLMENT";
        public static readonly string ICP_UPDATE_ENVELOPSTATUSAGAINSTDOCUSIGNROLE = "ICP_UPDATE_ENVELOPSTATUSAGAINSTDOCUSIGNROLE";
        public static readonly string ICP_GET_ENVELOPSTATUSAGAINSTDOCUSIGNROLE = "ICP_GET_ENVELOPSTATUSAGAINSTDOCUSIGNROLE";
        //Stop

        public static readonly string ICP_SELECT_LEARNINGSESSION = "ICP_SELECT_LEARNINGSESSION_BY_LEARNINGSESSIONID";
        public static readonly string ICP_GET_COURSEID_BY_LEARNINGSESSIONGUID = "ICP_GET_COURSEID_BY_LEARNINGSESSIONGUID";

        public static readonly string ICP_GET_LEARNER_TIMESPENT = "ICP_GET_LEARNER_TIMESPENT";
    }
}
