//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5477.
// 
#pragma warning disable 1591

namespace ICP4.BusinessLogic.ICPBrandingService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BrandingServiceSoap", Namespace="http://www.360training.com/")]
    public partial class BrandingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCourseInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLocaleInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBrandLocaleInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BrandingService() {
            this.Url = global::ICP4.BusinessLogic.Properties.Settings.Default.ICP4_BusinessLogic_ICPBrandingService_BrandingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCourseInfoCompletedEventHandler GetCourseInfoCompleted;
        
        /// <remarks/>
        public event GetLocaleInfoCompletedEventHandler GetLocaleInfoCompleted;
        
        /// <remarks/>
        public event GetBrandLocaleInfoCompletedEventHandler GetBrandLocaleInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.360training.com/GetCourseInfo", RequestNamespace="http://www.360training.com/", ResponseNamespace="http://www.360training.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCourseInfo() {
            object[] results = this.Invoke("GetCourseInfo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCourseInfoAsync() {
            this.GetCourseInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetCourseInfoAsync(object userState) {
            if ((this.GetCourseInfoOperationCompleted == null)) {
                this.GetCourseInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCourseInfoOperationCompleted);
            }
            this.InvokeAsync("GetCourseInfo", new object[0], this.GetCourseInfoOperationCompleted, userState);
        }
        
        private void OnGetCourseInfoOperationCompleted(object arg) {
            if ((this.GetCourseInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCourseInfoCompleted(this, new GetCourseInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.360training.com/GetLocaleInfo", RequestNamespace="http://www.360training.com/", ResponseNamespace="http://www.360training.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BrandLocaleInfo GetLocaleInfo(int courseID, int brandID, int localeID) {
            object[] results = this.Invoke("GetLocaleInfo", new object[] {
                        courseID,
                        brandID,
                        localeID});
            return ((BrandLocaleInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetLocaleInfoAsync(int courseID, int brandID, int localeID) {
            this.GetLocaleInfoAsync(courseID, brandID, localeID, null);
        }
        
        /// <remarks/>
        public void GetLocaleInfoAsync(int courseID, int brandID, int localeID, object userState) {
            if ((this.GetLocaleInfoOperationCompleted == null)) {
                this.GetLocaleInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLocaleInfoOperationCompleted);
            }
            this.InvokeAsync("GetLocaleInfo", new object[] {
                        courseID,
                        brandID,
                        localeID}, this.GetLocaleInfoOperationCompleted, userState);
        }
        
        private void OnGetLocaleInfoOperationCompleted(object arg) {
            if ((this.GetLocaleInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLocaleInfoCompleted(this, new GetLocaleInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.360training.com/GetBrandLocaleInfo", RequestNamespace="http://www.360training.com/", ResponseNamespace="http://www.360training.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BrandLocaleInfo GetBrandLocaleInfo(string brandCode, string variant) {
            object[] results = this.Invoke("GetBrandLocaleInfo", new object[] {
                        brandCode,
                        variant});
            return ((BrandLocaleInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetBrandLocaleInfoAsync(string brandCode, string variant) {
            this.GetBrandLocaleInfoAsync(brandCode, variant, null);
        }
        
        /// <remarks/>
        public void GetBrandLocaleInfoAsync(string brandCode, string variant, object userState) {
            if ((this.GetBrandLocaleInfoOperationCompleted == null)) {
                this.GetBrandLocaleInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBrandLocaleInfoOperationCompleted);
            }
            this.InvokeAsync("GetBrandLocaleInfo", new object[] {
                        brandCode,
                        variant}, this.GetBrandLocaleInfoOperationCompleted, userState);
        }
        
        private void OnGetBrandLocaleInfoOperationCompleted(object arg) {
            if ((this.GetBrandLocaleInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBrandLocaleInfoCompleted(this, new GetBrandLocaleInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.360training.com/")]
    public partial class BrandLocaleInfo {
        
        private int brandIDField;
        
        private string brandNameField;
        
        private int localeIDField;
        
        private LocaleResource[] localeResourceListField;
        
        /// <remarks/>
        public int BrandID {
            get {
                return this.brandIDField;
            }
            set {
                this.brandIDField = value;
            }
        }
        
        /// <remarks/>
        public string BrandName {
            get {
                return this.brandNameField;
            }
            set {
                this.brandNameField = value;
            }
        }
        
        /// <remarks/>
        public int LocaleID {
            get {
                return this.localeIDField;
            }
            set {
                this.localeIDField = value;
            }
        }
        
        /// <remarks/>
        public LocaleResource[] LocaleResourceList {
            get {
                return this.localeResourceListField;
            }
            set {
                this.localeResourceListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.360training.com/")]
    public partial class LocaleResource {
        
        private string resourceKeyField;
        
        private string resourceValueField;
        
        /// <remarks/>
        public string ResourceKey {
            get {
                return this.resourceKeyField;
            }
            set {
                this.resourceKeyField = value;
            }
        }
        
        /// <remarks/>
        public string ResourceValue {
            get {
                return this.resourceValueField;
            }
            set {
                this.resourceValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void GetCourseInfoCompletedEventHandler(object sender, GetCourseInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCourseInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCourseInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void GetLocaleInfoCompletedEventHandler(object sender, GetLocaleInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLocaleInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLocaleInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BrandLocaleInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BrandLocaleInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void GetBrandLocaleInfoCompletedEventHandler(object sender, GetBrandLocaleInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBrandLocaleInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBrandLocaleInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BrandLocaleInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BrandLocaleInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591