//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4206
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4206.
// 
#pragma warning disable 1591

namespace _360Training.TrackingService.LearningSessionComplete {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="lmsLcmsSoap11", Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
    public partial class lmsLcmsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LearnerSetupOperationCompleted;
        
        private System.Threading.SendOrPostCallback LearningSessionCompleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback PublishCourseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public lmsLcmsService() {
            this.Url = global::_360Training.TrackingService.Properties.Settings.Default._360Training_TrackingService_LearningSessionComplete_lmsLcmsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LearnerSetupCompletedEventHandler LearnerSetupCompleted;
        
        /// <remarks/>
        public event LearningSessionCompleteCompletedEventHandler LearningSessionCompleteCompleted;
        
        /// <remarks/>
        public event UpdateProfileCompletedEventHandler UpdateProfileCompleted;
        
        /// <remarks/>
        public event PublishCourseCompletedEventHandler PublishCourseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("LearnerSetupResponse", Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
        public LearnerSetupResponse LearnerSetup([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")] LearnerSetupRequest LearnerSetupRequest) {
            object[] results = this.Invoke("LearnerSetup", new object[] {
                        LearnerSetupRequest});
            return ((LearnerSetupResponse)(results[0]));
        }
        
        /// <remarks/>
        public void LearnerSetupAsync(LearnerSetupRequest LearnerSetupRequest) {
            this.LearnerSetupAsync(LearnerSetupRequest, null);
        }
        
        /// <remarks/>
        public void LearnerSetupAsync(LearnerSetupRequest LearnerSetupRequest, object userState) {
            if ((this.LearnerSetupOperationCompleted == null)) {
                this.LearnerSetupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLearnerSetupOperationCompleted);
            }
            this.InvokeAsync("LearnerSetup", new object[] {
                        LearnerSetupRequest}, this.LearnerSetupOperationCompleted, userState);
        }
        
        private void OnLearnerSetupOperationCompleted(object arg) {
            if ((this.LearnerSetupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LearnerSetupCompleted(this, new LearnerSetupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("LearningSessionCompleteResponse", Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
        public LearningSessionCompleteResponse LearningSessionComplete([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")] LearningSessionCompleteRequest LearningSessionCompleteRequest) {
            object[] results = this.Invoke("LearningSessionComplete", new object[] {
                        LearningSessionCompleteRequest});
            return ((LearningSessionCompleteResponse)(results[0]));
        }
        
        /// <remarks/>
        public void LearningSessionCompleteAsync(LearningSessionCompleteRequest LearningSessionCompleteRequest) {
            this.LearningSessionCompleteAsync(LearningSessionCompleteRequest, null);
        }
        
        /// <remarks/>
        public void LearningSessionCompleteAsync(LearningSessionCompleteRequest LearningSessionCompleteRequest, object userState) {
            if ((this.LearningSessionCompleteOperationCompleted == null)) {
                this.LearningSessionCompleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLearningSessionCompleteOperationCompleted);
            }
            this.InvokeAsync("LearningSessionComplete", new object[] {
                        LearningSessionCompleteRequest}, this.LearningSessionCompleteOperationCompleted, userState);
        }
        
        private void OnLearningSessionCompleteOperationCompleted(object arg) {
            if ((this.LearningSessionCompleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LearningSessionCompleteCompleted(this, new LearningSessionCompleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateProfileResponse", Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
        public UpdateProfileResponse UpdateProfile([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")] UpdateProfileRequest UpdateProfileRequest) {
            object[] results = this.Invoke("UpdateProfile", new object[] {
                        UpdateProfileRequest});
            return ((UpdateProfileResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateProfileAsync(UpdateProfileRequest UpdateProfileRequest) {
            this.UpdateProfileAsync(UpdateProfileRequest, null);
        }
        
        /// <remarks/>
        public void UpdateProfileAsync(UpdateProfileRequest UpdateProfileRequest, object userState) {
            if ((this.UpdateProfileOperationCompleted == null)) {
                this.UpdateProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProfileOperationCompleted);
            }
            this.InvokeAsync("UpdateProfile", new object[] {
                        UpdateProfileRequest}, this.UpdateProfileOperationCompleted, userState);
        }
        
        private void OnUpdateProfileOperationCompleted(object arg) {
            if ((this.UpdateProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateProfileCompleted(this, new UpdateProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PublishCourseResponse", Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
        public PublishCourseResponse PublishCourse([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")] PublishCourseRequest PublishCourseRequest) {
            object[] results = this.Invoke("PublishCourse", new object[] {
                        PublishCourseRequest});
            return ((PublishCourseResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PublishCourseAsync(PublishCourseRequest PublishCourseRequest) {
            this.PublishCourseAsync(PublishCourseRequest, null);
        }
        
        /// <remarks/>
        public void PublishCourseAsync(PublishCourseRequest PublishCourseRequest, object userState) {
            if ((this.PublishCourseOperationCompleted == null)) {
                this.PublishCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPublishCourseOperationCompleted);
            }
            this.InvokeAsync("PublishCourse", new object[] {
                        PublishCourseRequest}, this.PublishCourseOperationCompleted, userState);
        }
        
        private void OnPublishCourseOperationCompleted(object arg) {
            if ((this.PublishCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PublishCourseCompleted(this, new PublishCourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
    public partial class LearnerSetupRequest {
        
        private VU360User[] userListField;
        
        private string transactionGUIDField;
        
        private System.DateTime eventDateField;
        
        private string contentOwnerGUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userList")]
        public VU360User[] userList {
            get {
                return this.userListField;
            }
            set {
                this.userListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transactionGUID {
            get {
                return this.transactionGUIDField;
            }
            set {
                this.transactionGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime eventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentOwnerGUID {
            get {
                return this.contentOwnerGUIDField;
            }
            set {
                this.contentOwnerGUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
    public partial class VU360User {
        
        private LearnerProfile learnerProfileField;
        
        private string userGUIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        private string emailAddressField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public LearnerProfile learnerProfile {
            get {
                return this.learnerProfileField;
            }
            set {
                this.learnerProfileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userGUID {
            get {
                return this.userGUIDField;
            }
            set {
                this.userGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
    public partial class LearnerProfile {
        
        private Address billingAddressField;
        
        private Address shippingAddressField;
        
        private string mobilePhoneField;
        
        private string officePhoneField;
        
        private string officePhoneExtField;
        
        /// <remarks/>
        public Address billingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        public Address shippingAddress {
            get {
                return this.shippingAddressField;
            }
            set {
                this.shippingAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string officePhone {
            get {
                return this.officePhoneField;
            }
            set {
                this.officePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string officePhoneExt {
            get {
                return this.officePhoneExtField;
            }
            set {
                this.officePhoneExtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
    public partial class Address {
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string addressLine3Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipCodeField;
        
        private string countryField;
        
        /// <remarks/>
        public string addressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        public string addressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        public string addressLine3 {
            get {
                return this.addressLine3Field;
            }
            set {
                this.addressLine3Field = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
    public partial class CourseVO {
        
        private string guidField;
        
        /// <remarks/>
        public string guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
    public partial class ContentOwnerVO {
        
        private CourseVO[] courseListField;
        
        private string contentOwnerGUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("courseList")]
        public CourseVO[] courseList {
            get {
                return this.courseListField;
            }
            set {
                this.courseListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentOwnerGUID {
            get {
                return this.contentOwnerGUIDField;
            }
            set {
                this.contentOwnerGUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
    public partial class LearnerSetupResponse {
        
        private string transactionGUIDField;
        
        private System.DateTime eventDateField;
        
        private TransactionResultType transactionResultField;
        
        private string transactionResultMessageField;
        
        private string noOfLearnerSetupSuccessfullyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transactionGUID {
            get {
                return this.transactionGUIDField;
            }
            set {
                this.transactionGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime eventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TransactionResultType transactionResult {
            get {
                return this.transactionResultField;
            }
            set {
                this.transactionResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transactionResultMessage {
            get {
                return this.transactionResultMessageField;
            }
            set {
                this.transactionResultMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string noOfLearnerSetupSuccessfully {
            get {
                return this.noOfLearnerSetupSuccessfullyField;
            }
            set {
                this.noOfLearnerSetupSuccessfullyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
    public enum TransactionResultType {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failure,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
    public partial class LearningSessionCompleteRequest {
        
        private string transactionGUIDField;
        
        private System.DateTime eventDateField;
        
        private bool eventDateFieldSpecified;
        
        private string learningSessionIdField;
        
        private bool courseCompletedField;
        
        private bool courseCompletedFieldSpecified;
        
        private string certificateURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transactionGUID {
            get {
                return this.transactionGUIDField;
            }
            set {
                this.transactionGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime eventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventDateSpecified {
            get {
                return this.eventDateFieldSpecified;
            }
            set {
                this.eventDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string learningSessionId {
            get {
                return this.learningSessionIdField;
            }
            set {
                this.learningSessionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool courseCompleted {
            get {
                return this.courseCompletedField;
            }
            set {
                this.courseCompletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool courseCompletedSpecified {
            get {
                return this.courseCompletedFieldSpecified;
            }
            set {
                this.courseCompletedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string certificateURL {
            get {
                return this.certificateURLField;
            }
            set {
                this.certificateURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
    public partial class LearningSessionCompleteResponse {
        
        private string transactionGUIDField;
        
        private System.DateTime eventDateField;
        
        private TransactionResultType transactionResultField;
        
        private string transactionResultMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transactionGUID {
            get {
                return this.transactionGUIDField;
            }
            set {
                this.transactionGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime eventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TransactionResultType transactionResult {
            get {
                return this.transactionResultField;
            }
            set {
                this.transactionResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transactionResultMessage {
            get {
                return this.transactionResultMessageField;
            }
            set {
                this.transactionResultMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
    public partial class UpdateProfileRequest {
        
        private VU360User userField;
        
        private string transactionGUIDField;
        
        private System.DateTime eventDateField;
        
        /// <remarks/>
        public VU360User user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transactionGUID {
            get {
                return this.transactionGUIDField;
            }
            set {
                this.transactionGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime eventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
    public partial class UpdateProfileResponse {
        
        private string transactionGUIDField;
        
        private System.DateTime eventDateField;
        
        private TransactionResultType transactionResultField;
        
        private string transactionResultMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transactionGUID {
            get {
                return this.transactionGUIDField;
            }
            set {
                this.transactionGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime eventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TransactionResultType transactionResult {
            get {
                return this.transactionResultField;
            }
            set {
                this.transactionResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transactionResultMessage {
            get {
                return this.transactionResultMessageField;
            }
            set {
                this.transactionResultMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
    public partial class PublishCourseRequest {
        
        private ContentOwnerVO[] contentOwnerListField;
        
        private string transactionGUIDField;
        
        private System.DateTime eventDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contentOwnerList")]
        public ContentOwnerVO[] contentOwnerList {
            get {
                return this.contentOwnerListField;
            }
            set {
                this.contentOwnerListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transactionGUID {
            get {
                return this.transactionGUIDField;
            }
            set {
                this.transactionGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime eventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.360training.com/vu360/schemas/lms/lcmsMessages")]
    public partial class PublishCourseResponse {
        
        private string transactionGUIDField;
        
        private System.DateTime eventDateField;
        
        private TransactionResultType transactionResultField;
        
        private string transactionResultMessageField;
        
        private string noOfCoursesPublishedSuccessfullyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transactionGUID {
            get {
                return this.transactionGUIDField;
            }
            set {
                this.transactionGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime eventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TransactionResultType transactionResult {
            get {
                return this.transactionResultField;
            }
            set {
                this.transactionResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transactionResultMessage {
            get {
                return this.transactionResultMessageField;
            }
            set {
                this.transactionResultMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string noOfCoursesPublishedSuccessfully {
            get {
                return this.noOfCoursesPublishedSuccessfullyField;
            }
            set {
                this.noOfCoursesPublishedSuccessfullyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void LearnerSetupCompletedEventHandler(object sender, LearnerSetupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LearnerSetupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LearnerSetupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LearnerSetupResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LearnerSetupResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void LearningSessionCompleteCompletedEventHandler(object sender, LearningSessionCompleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LearningSessionCompleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LearningSessionCompleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LearningSessionCompleteResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LearningSessionCompleteResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void UpdateProfileCompletedEventHandler(object sender, UpdateProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateProfileResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateProfileResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void PublishCourseCompletedEventHandler(object sender, PublishCourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PublishCourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PublishCourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PublishCourseResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PublishCourseResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591