using System;
using System.Collections.Generic;
using System.Text;

namespace _360Training.AssessmentServiceDataLogic.Common
{
    public class StoredProcedures
    {
        public static readonly string SELECT_COURSE_PREASSESSMENT_ASSESSMENTITEM = "ICP_SELECT_COURSE_PREASSESSMENT_ASSESSMENTITEM";
        public static readonly string ICP_SELECT_COURSE_EXAM_ASSESSMENTITEM = "ICP_SELECT_COURSE_EXAM_ASSESSMENTITEM";
        public static readonly string SELECT_ASSESSMENTITEM_ASSESSMENTITEMANSWER = "ICP_SELECT_ASSESSMENTITEM_ASSESSMENTITEMANSWER";
        public static readonly string SELECT_ASSET_LOCATION = "ICP_SELECT_ASSET_LOCATION";
        public static readonly string SELECT_ASSESSMENTITEMANSWER_IMAGETARGETCOORDINATE = "ICP_SELECT_ASSESSMENTITEMANSWER_IMAGETARGETCOORDINATE";
        public static readonly string SELECT_COURSE_POSTASSESSMENT_ASSESSMENTITEM = "ICP_SELECT_COURSE_POSTASSESSMENT_ASSESSMENTITEM";
        public static readonly string SELECT_CONTENTOBJECT_ASSESSMENTITEMS = "ICP_SELECT_CONTENTOBJECT_ASSESSMENTITEMS";
        public static readonly string SELECT_ASSESSMENTITEM_SCENE = "ICP_SELECT_ASSESSMENTITEM_SCENE";
        public static readonly string SELECT_ASSESSMENTITEM_ASSESSMENTITEMTEMPLATE = "ICP_SELECT_ASSESSMENTITEM_ASSESSMENTITEMTEMPLATE";
        public static readonly string SELECT_ASSESSMENTITEM_ASSETS = "ICP_SELECT_ASSESSMENTITEM_ASSETS";
        public static readonly string SELECT_SCENE_ASSESSMENTITEMS = "ICP_SELECT_SCENE_ASSESSMENTITEMS";
        public static readonly string SELECT_ASSESSMENTITEMBANKS_FOR_RANDOMALTERNATE = "ICP_SELECT_ASSESSMENTITEMBANKS_FOR_RANDOMALTERNATE";
        public static readonly string SELECT_ASSESSMENTITEMS_BY_ASSESSMENTITEMBANKID = "ICP_SELECT_ASSESSMENTITEMS_BY_ASSESSMENTITEMBANKID";
        public static readonly string SELECT_ASSESSMENTITEMS_BY_ASSESSMENTITEMBANKIDS = "ICP_SELECT_ASSESSMENTITEMS_BY_ASSESSMENTITEMBANKIDS"; // LCMS-9882

        public static readonly string SELECT_ASSESSMENTITEMS_BY_TESTID = "ICP_SELECT_ASSESSMENTITEMS_BY_TESTID";
        public static readonly string SELECT_ASSESSMENTITEMBANKS_FOR_RANDOMALTERNATEMULTIPLEITEMBANK = "ICP_SELECT_ASSESSMENTITEMBANKS_FOR_RANDOMALTERNATEMULTIPLEITEMBANK";
        public static readonly string ICP_SELECT_LEARNINGOBJECTIVE_POST = "ICP_SELECT_LEARNINGOBJECTIVE_POST";
        public static readonly string ICP_SELECT_EXAM_TOPIC_FORADVANCE = "ICP_SELECT_EXAM_TOPIC_FORADVANCE";
        public static readonly string ICP_SELECT_LEARNINGOBJECTIVE_PRE = "ICP_SELECT_LEARNINGOBJECTIVE_PRE";
        public static readonly string ICP_SELECT_LEARNINGOBJECTIVE_QUIZ = "ICP_SELECT_LEARNINGOBJECTIVE_QUIZ";
        public static readonly string ICP_SELECT_ASSESSMENTITEMID_LEARNINGOBJECTIVE = "ICP_SELECT_ASSESSMENTITEMID_LEARNINGOBJECTIVE";
        public static readonly string ICP_SELECT_ASSESSMENTITEM_SPLT = "ICP_SELECT_ASSESSMENTITEM_SPLT";
        public static readonly string ICP_SELECT_ASSESSMENTITEMID_TOPIC = "ICP_SELECT_ASSESSMENTITEMID_TOPIC";

        public static readonly string ICP_SELECT_ASSESSMENTITEMID_RESULT = "ICP_SELECT_ASSESSMENTITEM_RESULTS";

    }
}
