//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4952.
// 
#pragma warning disable 1591

namespace ICP4.CoursePlayer.ICP4PlayerUtility {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PlayerUtilitySoap", Namespace="http://tempuri.org/")]
    public partial class PlayerUtility : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddUpdateCacheOperationCompleted;
        
        private System.Threading.SendOrPostCallback InvalidateCacheOperationCompleted;
        
        private System.Threading.SendOrPostCallback InvalidateCacheAndNotifyToAllRemainingServersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PlayerUtility() {
            this.Url = global::ICP4.CoursePlayer.Properties.Settings.Default.ICP4_CoursePlayer_ICP4PlayerUtility_PlayerUtility;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event AddUpdateCacheCompletedEventHandler AddUpdateCacheCompleted;
        
        /// <remarks/>
        public event InvalidateCacheCompletedEventHandler InvalidateCacheCompleted;
        
        /// <remarks/>
        public event InvalidateCacheAndNotifyToAllRemainingServersCompletedEventHandler InvalidateCacheAndNotifyToAllRemainingServersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddUpdateCache", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddUpdateCache(int publishedCourseId, CourseConfiguration courseConfiguration, Sequence courseSequence, Sequence courseDemoSequence, TableOfContent courseTOC) {
            object[] results = this.Invoke("AddUpdateCache", new object[] {
                        publishedCourseId,
                        courseConfiguration,
                        courseSequence,
                        courseDemoSequence,
                        courseTOC});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddUpdateCacheAsync(int publishedCourseId, CourseConfiguration courseConfiguration, Sequence courseSequence, Sequence courseDemoSequence, TableOfContent courseTOC) {
            this.AddUpdateCacheAsync(publishedCourseId, courseConfiguration, courseSequence, courseDemoSequence, courseTOC, null);
        }
        
        /// <remarks/>
        public void AddUpdateCacheAsync(int publishedCourseId, CourseConfiguration courseConfiguration, Sequence courseSequence, Sequence courseDemoSequence, TableOfContent courseTOC, object userState) {
            if ((this.AddUpdateCacheOperationCompleted == null)) {
                this.AddUpdateCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUpdateCacheOperationCompleted);
            }
            this.InvokeAsync("AddUpdateCache", new object[] {
                        publishedCourseId,
                        courseConfiguration,
                        courseSequence,
                        courseDemoSequence,
                        courseTOC}, this.AddUpdateCacheOperationCompleted, userState);
        }
        
        private void OnAddUpdateCacheOperationCompleted(object arg) {
            if ((this.AddUpdateCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUpdateCacheCompleted(this, new AddUpdateCacheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InvalidateCache", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InvalidateCache(int publishedCourseId) {
            object[] results = this.Invoke("InvalidateCache", new object[] {
                        publishedCourseId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InvalidateCacheAsync(int publishedCourseId) {
            this.InvalidateCacheAsync(publishedCourseId, null);
        }
        
        /// <remarks/>
        public void InvalidateCacheAsync(int publishedCourseId, object userState) {
            if ((this.InvalidateCacheOperationCompleted == null)) {
                this.InvalidateCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInvalidateCacheOperationCompleted);
            }
            this.InvokeAsync("InvalidateCache", new object[] {
                        publishedCourseId}, this.InvalidateCacheOperationCompleted, userState);
        }
        
        private void OnInvalidateCacheOperationCompleted(object arg) {
            if ((this.InvalidateCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InvalidateCacheCompleted(this, new InvalidateCacheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InvalidateCacheAndNotifyToAllRemainingServers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InvalidateCacheAndNotifyToAllRemainingServers(int publishedCourseId, bool notifytoAllRemainingServers) {
            object[] results = this.Invoke("InvalidateCacheAndNotifyToAllRemainingServers", new object[] {
                        publishedCourseId,
                        notifytoAllRemainingServers});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InvalidateCacheAndNotifyToAllRemainingServersAsync(int publishedCourseId, bool notifytoAllRemainingServers) {
            this.InvalidateCacheAndNotifyToAllRemainingServersAsync(publishedCourseId, notifytoAllRemainingServers, null);
        }
        
        /// <remarks/>
        public void InvalidateCacheAndNotifyToAllRemainingServersAsync(int publishedCourseId, bool notifytoAllRemainingServers, object userState) {
            if ((this.InvalidateCacheAndNotifyToAllRemainingServersOperationCompleted == null)) {
                this.InvalidateCacheAndNotifyToAllRemainingServersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInvalidateCacheAndNotifyToAllRemainingServersOperationCompleted);
            }
            this.InvokeAsync("InvalidateCacheAndNotifyToAllRemainingServers", new object[] {
                        publishedCourseId,
                        notifytoAllRemainingServers}, this.InvalidateCacheAndNotifyToAllRemainingServersOperationCompleted, userState);
        }
        
        private void OnInvalidateCacheAndNotifyToAllRemainingServersOperationCompleted(object arg) {
            if ((this.InvalidateCacheAndNotifyToAllRemainingServersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InvalidateCacheAndNotifyToAllRemainingServersCompleted(this, new InvalidateCacheAndNotifyToAllRemainingServersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.360training.com/")]
    public partial class CourseConfiguration {
        
        private int courseConfigurationIDField;
        
        private bool playerEnableIntroPageField;
        
        private bool playerEnableContentField;
        
        private bool playerEnableEndOfCourseSceneField;
        
        private bool playerAllowUserToReviewCourseAfterCompletionField;
        
        private int playerIdleUserTimeoutField;
        
        private string playerCourseFlowField;
        
        private bool playerEnforceTimedOutlineField;
        
        private bool playerEnableOrientaionScenesField;
        
        private bool playerCourseEvaluationField;
        
        private string playerDisplayCourseEvaluationField;
        
        private bool playerMustCompleteCourseEvaluatioField;
        
        private string playerCourseEvaluationInstructionsField;
        
        private bool completionPostAssessmentAttemptedField;
        
        private bool completionPostAssessmentMasteryField;
        
        private bool completionPreAssessmentMasteryField;
        
        private bool completionQuizMasteryField;
        
        private bool completionSurveyField;
        
        private bool completionViewEverySceneInCourseField;
        
        private int completionCompleteAfterNOUniqueCourseVisitField;
        
        private int completionMustCompleteWithinSpecifiedAmountOfTimeMinuteField;
        
        private int completionMustCompleteWithinSpecifiedAmountOfTimeDayField;
        
        private bool certificateEnabledField;
        
        private int certificateAssetIDField;
        
        private string completionUnitOfMustCompleteWithInSpecifiedAmountOfTimeField;
        
        private bool completionRespondToCourseEvaluationField;
        
        private bool preAssessmentEnabledField;
        
        private int preAssessmentNOQuestionField;
        
        private int preAssessmentMasteryScoreField;
        
        private bool preAssessmentRandomizeQuestionField;
        
        private bool preAssessmentRandomizeAnswersField;
        
        private int preAssessmentEnforceMaximumTimeLimitField;
        
        private int preAssessmentMaximumNOAttemptField;
        
        private string preAssessmentActionToTakeAfterFailingMaxAttemptField;
        
        private string preAssessmentScoreTypeField;
        
        private bool preAssessmentProctoredAssessmentField;
        
        private bool preAssessmentAllowSkippingQuestionField;
        
        private bool preAssessmentEnforceUniqueQuestionsOnRetakeField;
        
        private bool preAssessmentQuestionLevelResultField;
        
        private bool preAssessmentContentRemediationField;
        
        private bool preAssessmentScoreAsYouGoField;
        
        private bool preAssessmentShowQuestionAnswerSummaryField;
        
        private bool preAssessmentAllowPauseResumeAssessmentField;
        
        private bool preAssessmentRestrictiveModeField;
        
        private bool postAssessmentEnabledField;
        
        private int postAssessmentNOQuestionField;
        
        private int postAssessmentMasteryScoreField;
        
        private bool postAssessmentRandomizeQuestionField;
        
        private bool postAssessmentRandomizeAnswersField;
        
        private int postAssessmentEnforceMaximumTimeLimitField;
        
        private int postAssessmentMaximumNOAttemptField;
        
        private string postAssessmentActionToTakeAfterFailingMaxAttemptField;
        
        private string postAssessmentScoreTypeField;
        
        private bool postAssessmentProctoredAssessmentField;
        
        private bool postAssessmentAllowSkippingQuestionField;
        
        private bool postAssessmentEnforceUniqueQuestionsOnRetakeField;
        
        private bool postAssessmentQuestionLevelResultField;
        
        private bool postAssessmentContentRemediationField;
        
        private bool postAssessmentScoreAsYouGoField;
        
        private bool postAssessmentShowQuestionAnswerSummaryField;
        
        private bool postAssessmentAllowPauseResumeAssessmentField;
        
        private bool postAssessmentRestrictiveModeField;
        
        private int postAssessmentMinimumTimeBeforeStartField;
        
        private string postAssessmentMinimumTimeBeforeStartUnitField;
        
        private bool quizEnabledField;
        
        private int quizNOQuestionField;
        
        private int quizMasteryScoreField;
        
        private bool quizRandomizeQuestionField;
        
        private bool quizRandomizeAnswersField;
        
        private int quizEnforceMaximumTimeLimitField;
        
        private int quizMaximumNOAttemptField;
        
        private string quizActionToTakeAfterFailingMaxAttemptField;
        
        private string quizScoreTypeField;
        
        private bool quizProctoredAssessmentField;
        
        private bool quizAllowSkippingQuestionField;
        
        private bool quizEnforceUniqueQuestionsOnRetakeField;
        
        private bool quizQuestionLevelResultField;
        
        private bool quizContentRemediationField;
        
        private bool quizScoreAsYouGoField;
        
        private bool quizShowQuestionAnswerSummaryField;
        
        private bool quizAllowPauseResumeAssessmentField;
        
        private bool quizAssessmentRestrictiveModeField;
        
        private bool validationRequireIdentityValidationField;
        
        private int validationTimeBetweenQuestionField;
        
        private int validationTimeToAnswerQuestionField;
        
        private int validationNOMissedQuestionsAllowedField;
        
        private int validationNOValidationQuestionField;
        
        private bool embeddedAcknowledgmentEnabledField;
        
        private string embeddedAcknowledgmentTextField;
        
        private bool seatTimeEnabledField;
        
        private int seatTimeInHourField;
        
        private int seatTimeInMinField;
        
        private string messageSeatTimeExceedsField;
        
        private string messageSeatTimeCourseLaunchField;
        
        private string actionToTakeUponIdleTimeOutField;
        
        /// <remarks/>
        public int CourseConfigurationID {
            get {
                return this.courseConfigurationIDField;
            }
            set {
                this.courseConfigurationIDField = value;
            }
        }
        
        /// <remarks/>
        public bool PlayerEnableIntroPage {
            get {
                return this.playerEnableIntroPageField;
            }
            set {
                this.playerEnableIntroPageField = value;
            }
        }
        
        /// <remarks/>
        public bool PlayerEnableContent {
            get {
                return this.playerEnableContentField;
            }
            set {
                this.playerEnableContentField = value;
            }
        }
        
        /// <remarks/>
        public bool PlayerEnableEndOfCourseScene {
            get {
                return this.playerEnableEndOfCourseSceneField;
            }
            set {
                this.playerEnableEndOfCourseSceneField = value;
            }
        }
        
        /// <remarks/>
        public bool PlayerAllowUserToReviewCourseAfterCompletion {
            get {
                return this.playerAllowUserToReviewCourseAfterCompletionField;
            }
            set {
                this.playerAllowUserToReviewCourseAfterCompletionField = value;
            }
        }
        
        /// <remarks/>
        public int PlayerIdleUserTimeout {
            get {
                return this.playerIdleUserTimeoutField;
            }
            set {
                this.playerIdleUserTimeoutField = value;
            }
        }
        
        /// <remarks/>
        public string PlayerCourseFlow {
            get {
                return this.playerCourseFlowField;
            }
            set {
                this.playerCourseFlowField = value;
            }
        }
        
        /// <remarks/>
        public bool PlayerEnforceTimedOutline {
            get {
                return this.playerEnforceTimedOutlineField;
            }
            set {
                this.playerEnforceTimedOutlineField = value;
            }
        }
        
        /// <remarks/>
        public bool PlayerEnableOrientaionScenes {
            get {
                return this.playerEnableOrientaionScenesField;
            }
            set {
                this.playerEnableOrientaionScenesField = value;
            }
        }
        
        /// <remarks/>
        public bool PlayerCourseEvaluation {
            get {
                return this.playerCourseEvaluationField;
            }
            set {
                this.playerCourseEvaluationField = value;
            }
        }
        
        /// <remarks/>
        public string PlayerDisplayCourseEvaluation {
            get {
                return this.playerDisplayCourseEvaluationField;
            }
            set {
                this.playerDisplayCourseEvaluationField = value;
            }
        }
        
        /// <remarks/>
        public bool PlayerMustCompleteCourseEvaluatio {
            get {
                return this.playerMustCompleteCourseEvaluatioField;
            }
            set {
                this.playerMustCompleteCourseEvaluatioField = value;
            }
        }
        
        /// <remarks/>
        public string PlayerCourseEvaluationInstructions {
            get {
                return this.playerCourseEvaluationInstructionsField;
            }
            set {
                this.playerCourseEvaluationInstructionsField = value;
            }
        }
        
        /// <remarks/>
        public bool CompletionPostAssessmentAttempted {
            get {
                return this.completionPostAssessmentAttemptedField;
            }
            set {
                this.completionPostAssessmentAttemptedField = value;
            }
        }
        
        /// <remarks/>
        public bool CompletionPostAssessmentMastery {
            get {
                return this.completionPostAssessmentMasteryField;
            }
            set {
                this.completionPostAssessmentMasteryField = value;
            }
        }
        
        /// <remarks/>
        public bool CompletionPreAssessmentMastery {
            get {
                return this.completionPreAssessmentMasteryField;
            }
            set {
                this.completionPreAssessmentMasteryField = value;
            }
        }
        
        /// <remarks/>
        public bool CompletionQuizMastery {
            get {
                return this.completionQuizMasteryField;
            }
            set {
                this.completionQuizMasteryField = value;
            }
        }
        
        /// <remarks/>
        public bool CompletionSurvey {
            get {
                return this.completionSurveyField;
            }
            set {
                this.completionSurveyField = value;
            }
        }
        
        /// <remarks/>
        public bool CompletionViewEverySceneInCourse {
            get {
                return this.completionViewEverySceneInCourseField;
            }
            set {
                this.completionViewEverySceneInCourseField = value;
            }
        }
        
        /// <remarks/>
        public int CompletionCompleteAfterNOUniqueCourseVisit {
            get {
                return this.completionCompleteAfterNOUniqueCourseVisitField;
            }
            set {
                this.completionCompleteAfterNOUniqueCourseVisitField = value;
            }
        }
        
        /// <remarks/>
        public int CompletionMustCompleteWithinSpecifiedAmountOfTimeMinute {
            get {
                return this.completionMustCompleteWithinSpecifiedAmountOfTimeMinuteField;
            }
            set {
                this.completionMustCompleteWithinSpecifiedAmountOfTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int CompletionMustCompleteWithinSpecifiedAmountOfTimeDay {
            get {
                return this.completionMustCompleteWithinSpecifiedAmountOfTimeDayField;
            }
            set {
                this.completionMustCompleteWithinSpecifiedAmountOfTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public bool CertificateEnabled {
            get {
                return this.certificateEnabledField;
            }
            set {
                this.certificateEnabledField = value;
            }
        }
        
        /// <remarks/>
        public int CertificateAssetID {
            get {
                return this.certificateAssetIDField;
            }
            set {
                this.certificateAssetIDField = value;
            }
        }
        
        /// <remarks/>
        public string CompletionUnitOfMustCompleteWithInSpecifiedAmountOfTime {
            get {
                return this.completionUnitOfMustCompleteWithInSpecifiedAmountOfTimeField;
            }
            set {
                this.completionUnitOfMustCompleteWithInSpecifiedAmountOfTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool CompletionRespondToCourseEvaluation {
            get {
                return this.completionRespondToCourseEvaluationField;
            }
            set {
                this.completionRespondToCourseEvaluationField = value;
            }
        }
        
        /// <remarks/>
        public bool PreAssessmentEnabled {
            get {
                return this.preAssessmentEnabledField;
            }
            set {
                this.preAssessmentEnabledField = value;
            }
        }
        
        /// <remarks/>
        public int PreAssessmentNOQuestion {
            get {
                return this.preAssessmentNOQuestionField;
            }
            set {
                this.preAssessmentNOQuestionField = value;
            }
        }
        
        /// <remarks/>
        public int PreAssessmentMasteryScore {
            get {
                return this.preAssessmentMasteryScoreField;
            }
            set {
                this.preAssessmentMasteryScoreField = value;
            }
        }
        
        /// <remarks/>
        public bool PreAssessmentRandomizeQuestion {
            get {
                return this.preAssessmentRandomizeQuestionField;
            }
            set {
                this.preAssessmentRandomizeQuestionField = value;
            }
        }
        
        /// <remarks/>
        public bool PreAssessmentRandomizeAnswers {
            get {
                return this.preAssessmentRandomizeAnswersField;
            }
            set {
                this.preAssessmentRandomizeAnswersField = value;
            }
        }
        
        /// <remarks/>
        public int PreAssessmentEnforceMaximumTimeLimit {
            get {
                return this.preAssessmentEnforceMaximumTimeLimitField;
            }
            set {
                this.preAssessmentEnforceMaximumTimeLimitField = value;
            }
        }
        
        /// <remarks/>
        public int PreAssessmentMaximumNOAttempt {
            get {
                return this.preAssessmentMaximumNOAttemptField;
            }
            set {
                this.preAssessmentMaximumNOAttemptField = value;
            }
        }
        
        /// <remarks/>
        public string PreAssessmentActionToTakeAfterFailingMaxAttempt {
            get {
                return this.preAssessmentActionToTakeAfterFailingMaxAttemptField;
            }
            set {
                this.preAssessmentActionToTakeAfterFailingMaxAttemptField = value;
            }
        }
        
        /// <remarks/>
        public string PreAssessmentScoreType {
            get {
                return this.preAssessmentScoreTypeField;
            }
            set {
                this.preAssessmentScoreTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool PreAssessmentProctoredAssessment {
            get {
                return this.preAssessmentProctoredAssessmentField;
            }
            set {
                this.preAssessmentProctoredAssessmentField = value;
            }
        }
        
        /// <remarks/>
        public bool PreAssessmentAllowSkippingQuestion {
            get {
                return this.preAssessmentAllowSkippingQuestionField;
            }
            set {
                this.preAssessmentAllowSkippingQuestionField = value;
            }
        }
        
        /// <remarks/>
        public bool PreAssessmentEnforceUniqueQuestionsOnRetake {
            get {
                return this.preAssessmentEnforceUniqueQuestionsOnRetakeField;
            }
            set {
                this.preAssessmentEnforceUniqueQuestionsOnRetakeField = value;
            }
        }
        
        /// <remarks/>
        public bool PreAssessmentQuestionLevelResult {
            get {
                return this.preAssessmentQuestionLevelResultField;
            }
            set {
                this.preAssessmentQuestionLevelResultField = value;
            }
        }
        
        /// <remarks/>
        public bool PreAssessmentContentRemediation {
            get {
                return this.preAssessmentContentRemediationField;
            }
            set {
                this.preAssessmentContentRemediationField = value;
            }
        }
        
        /// <remarks/>
        public bool PreAssessmentScoreAsYouGo {
            get {
                return this.preAssessmentScoreAsYouGoField;
            }
            set {
                this.preAssessmentScoreAsYouGoField = value;
            }
        }
        
        /// <remarks/>
        public bool PreAssessmentShowQuestionAnswerSummary {
            get {
                return this.preAssessmentShowQuestionAnswerSummaryField;
            }
            set {
                this.preAssessmentShowQuestionAnswerSummaryField = value;
            }
        }
        
        /// <remarks/>
        public bool PreAssessmentAllowPauseResumeAssessment {
            get {
                return this.preAssessmentAllowPauseResumeAssessmentField;
            }
            set {
                this.preAssessmentAllowPauseResumeAssessmentField = value;
            }
        }
        
        /// <remarks/>
        public bool PreAssessmentRestrictiveMode {
            get {
                return this.preAssessmentRestrictiveModeField;
            }
            set {
                this.preAssessmentRestrictiveModeField = value;
            }
        }
        
        /// <remarks/>
        public bool PostAssessmentEnabled {
            get {
                return this.postAssessmentEnabledField;
            }
            set {
                this.postAssessmentEnabledField = value;
            }
        }
        
        /// <remarks/>
        public int PostAssessmentNOQuestion {
            get {
                return this.postAssessmentNOQuestionField;
            }
            set {
                this.postAssessmentNOQuestionField = value;
            }
        }
        
        /// <remarks/>
        public int PostAssessmentMasteryScore {
            get {
                return this.postAssessmentMasteryScoreField;
            }
            set {
                this.postAssessmentMasteryScoreField = value;
            }
        }
        
        /// <remarks/>
        public bool PostAssessmentRandomizeQuestion {
            get {
                return this.postAssessmentRandomizeQuestionField;
            }
            set {
                this.postAssessmentRandomizeQuestionField = value;
            }
        }
        
        /// <remarks/>
        public bool PostAssessmentRandomizeAnswers {
            get {
                return this.postAssessmentRandomizeAnswersField;
            }
            set {
                this.postAssessmentRandomizeAnswersField = value;
            }
        }
        
        /// <remarks/>
        public int PostAssessmentEnforceMaximumTimeLimit {
            get {
                return this.postAssessmentEnforceMaximumTimeLimitField;
            }
            set {
                this.postAssessmentEnforceMaximumTimeLimitField = value;
            }
        }
        
        /// <remarks/>
        public int PostAssessmentMaximumNOAttempt {
            get {
                return this.postAssessmentMaximumNOAttemptField;
            }
            set {
                this.postAssessmentMaximumNOAttemptField = value;
            }
        }
        
        /// <remarks/>
        public string PostAssessmentActionToTakeAfterFailingMaxAttempt {
            get {
                return this.postAssessmentActionToTakeAfterFailingMaxAttemptField;
            }
            set {
                this.postAssessmentActionToTakeAfterFailingMaxAttemptField = value;
            }
        }
        
        /// <remarks/>
        public string PostAssessmentScoreType {
            get {
                return this.postAssessmentScoreTypeField;
            }
            set {
                this.postAssessmentScoreTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool PostAssessmentProctoredAssessment {
            get {
                return this.postAssessmentProctoredAssessmentField;
            }
            set {
                this.postAssessmentProctoredAssessmentField = value;
            }
        }
        
        /// <remarks/>
        public bool PostAssessmentAllowSkippingQuestion {
            get {
                return this.postAssessmentAllowSkippingQuestionField;
            }
            set {
                this.postAssessmentAllowSkippingQuestionField = value;
            }
        }
        
        /// <remarks/>
        public bool PostAssessmentEnforceUniqueQuestionsOnRetake {
            get {
                return this.postAssessmentEnforceUniqueQuestionsOnRetakeField;
            }
            set {
                this.postAssessmentEnforceUniqueQuestionsOnRetakeField = value;
            }
        }
        
        /// <remarks/>
        public bool PostAssessmentQuestionLevelResult {
            get {
                return this.postAssessmentQuestionLevelResultField;
            }
            set {
                this.postAssessmentQuestionLevelResultField = value;
            }
        }
        
        /// <remarks/>
        public bool PostAssessmentContentRemediation {
            get {
                return this.postAssessmentContentRemediationField;
            }
            set {
                this.postAssessmentContentRemediationField = value;
            }
        }
        
        /// <remarks/>
        public bool PostAssessmentScoreAsYouGo {
            get {
                return this.postAssessmentScoreAsYouGoField;
            }
            set {
                this.postAssessmentScoreAsYouGoField = value;
            }
        }
        
        /// <remarks/>
        public bool PostAssessmentShowQuestionAnswerSummary {
            get {
                return this.postAssessmentShowQuestionAnswerSummaryField;
            }
            set {
                this.postAssessmentShowQuestionAnswerSummaryField = value;
            }
        }
        
        /// <remarks/>
        public bool PostAssessmentAllowPauseResumeAssessment {
            get {
                return this.postAssessmentAllowPauseResumeAssessmentField;
            }
            set {
                this.postAssessmentAllowPauseResumeAssessmentField = value;
            }
        }
        
        /// <remarks/>
        public bool PostAssessmentRestrictiveMode {
            get {
                return this.postAssessmentRestrictiveModeField;
            }
            set {
                this.postAssessmentRestrictiveModeField = value;
            }
        }
        
        /// <remarks/>
        public int PostAssessmentMinimumTimeBeforeStart {
            get {
                return this.postAssessmentMinimumTimeBeforeStartField;
            }
            set {
                this.postAssessmentMinimumTimeBeforeStartField = value;
            }
        }
        
        /// <remarks/>
        public string PostAssessmentMinimumTimeBeforeStartUnit {
            get {
                return this.postAssessmentMinimumTimeBeforeStartUnitField;
            }
            set {
                this.postAssessmentMinimumTimeBeforeStartUnitField = value;
            }
        }
        
        /// <remarks/>
        public bool QuizEnabled {
            get {
                return this.quizEnabledField;
            }
            set {
                this.quizEnabledField = value;
            }
        }
        
        /// <remarks/>
        public int QuizNOQuestion {
            get {
                return this.quizNOQuestionField;
            }
            set {
                this.quizNOQuestionField = value;
            }
        }
        
        /// <remarks/>
        public int QuizMasteryScore {
            get {
                return this.quizMasteryScoreField;
            }
            set {
                this.quizMasteryScoreField = value;
            }
        }
        
        /// <remarks/>
        public bool QuizRandomizeQuestion {
            get {
                return this.quizRandomizeQuestionField;
            }
            set {
                this.quizRandomizeQuestionField = value;
            }
        }
        
        /// <remarks/>
        public bool QuizRandomizeAnswers {
            get {
                return this.quizRandomizeAnswersField;
            }
            set {
                this.quizRandomizeAnswersField = value;
            }
        }
        
        /// <remarks/>
        public int QuizEnforceMaximumTimeLimit {
            get {
                return this.quizEnforceMaximumTimeLimitField;
            }
            set {
                this.quizEnforceMaximumTimeLimitField = value;
            }
        }
        
        /// <remarks/>
        public int QuizMaximumNOAttempt {
            get {
                return this.quizMaximumNOAttemptField;
            }
            set {
                this.quizMaximumNOAttemptField = value;
            }
        }
        
        /// <remarks/>
        public string QuizActionToTakeAfterFailingMaxAttempt {
            get {
                return this.quizActionToTakeAfterFailingMaxAttemptField;
            }
            set {
                this.quizActionToTakeAfterFailingMaxAttemptField = value;
            }
        }
        
        /// <remarks/>
        public string QuizScoreType {
            get {
                return this.quizScoreTypeField;
            }
            set {
                this.quizScoreTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool QuizProctoredAssessment {
            get {
                return this.quizProctoredAssessmentField;
            }
            set {
                this.quizProctoredAssessmentField = value;
            }
        }
        
        /// <remarks/>
        public bool QuizAllowSkippingQuestion {
            get {
                return this.quizAllowSkippingQuestionField;
            }
            set {
                this.quizAllowSkippingQuestionField = value;
            }
        }
        
        /// <remarks/>
        public bool QuizEnforceUniqueQuestionsOnRetake {
            get {
                return this.quizEnforceUniqueQuestionsOnRetakeField;
            }
            set {
                this.quizEnforceUniqueQuestionsOnRetakeField = value;
            }
        }
        
        /// <remarks/>
        public bool QuizQuestionLevelResult {
            get {
                return this.quizQuestionLevelResultField;
            }
            set {
                this.quizQuestionLevelResultField = value;
            }
        }
        
        /// <remarks/>
        public bool QuizContentRemediation {
            get {
                return this.quizContentRemediationField;
            }
            set {
                this.quizContentRemediationField = value;
            }
        }
        
        /// <remarks/>
        public bool QuizScoreAsYouGo {
            get {
                return this.quizScoreAsYouGoField;
            }
            set {
                this.quizScoreAsYouGoField = value;
            }
        }
        
        /// <remarks/>
        public bool QuizShowQuestionAnswerSummary {
            get {
                return this.quizShowQuestionAnswerSummaryField;
            }
            set {
                this.quizShowQuestionAnswerSummaryField = value;
            }
        }
        
        /// <remarks/>
        public bool QuizAllowPauseResumeAssessment {
            get {
                return this.quizAllowPauseResumeAssessmentField;
            }
            set {
                this.quizAllowPauseResumeAssessmentField = value;
            }
        }
        
        /// <remarks/>
        public bool QuizAssessmentRestrictiveMode {
            get {
                return this.quizAssessmentRestrictiveModeField;
            }
            set {
                this.quizAssessmentRestrictiveModeField = value;
            }
        }
        
        /// <remarks/>
        public bool ValidationRequireIdentityValidation {
            get {
                return this.validationRequireIdentityValidationField;
            }
            set {
                this.validationRequireIdentityValidationField = value;
            }
        }
        
        /// <remarks/>
        public int ValidationTimeBetweenQuestion {
            get {
                return this.validationTimeBetweenQuestionField;
            }
            set {
                this.validationTimeBetweenQuestionField = value;
            }
        }
        
        /// <remarks/>
        public int ValidationTimeToAnswerQuestion {
            get {
                return this.validationTimeToAnswerQuestionField;
            }
            set {
                this.validationTimeToAnswerQuestionField = value;
            }
        }
        
        /// <remarks/>
        public int ValidationNOMissedQuestionsAllowed {
            get {
                return this.validationNOMissedQuestionsAllowedField;
            }
            set {
                this.validationNOMissedQuestionsAllowedField = value;
            }
        }
        
        /// <remarks/>
        public int ValidationNOValidationQuestion {
            get {
                return this.validationNOValidationQuestionField;
            }
            set {
                this.validationNOValidationQuestionField = value;
            }
        }
        
        /// <remarks/>
        public bool EmbeddedAcknowledgmentEnabled {
            get {
                return this.embeddedAcknowledgmentEnabledField;
            }
            set {
                this.embeddedAcknowledgmentEnabledField = value;
            }
        }
        
        /// <remarks/>
        public string EmbeddedAcknowledgmentText {
            get {
                return this.embeddedAcknowledgmentTextField;
            }
            set {
                this.embeddedAcknowledgmentTextField = value;
            }
        }
        
        /// <remarks/>
        public bool SeatTimeEnabled {
            get {
                return this.seatTimeEnabledField;
            }
            set {
                this.seatTimeEnabledField = value;
            }
        }
        
        /// <remarks/>
        public int SeatTimeInHour {
            get {
                return this.seatTimeInHourField;
            }
            set {
                this.seatTimeInHourField = value;
            }
        }
        
        /// <remarks/>
        public int SeatTimeInMin {
            get {
                return this.seatTimeInMinField;
            }
            set {
                this.seatTimeInMinField = value;
            }
        }
        
        /// <remarks/>
        public string MessageSeatTimeExceeds {
            get {
                return this.messageSeatTimeExceedsField;
            }
            set {
                this.messageSeatTimeExceedsField = value;
            }
        }
        
        /// <remarks/>
        public string MessageSeatTimeCourseLaunch {
            get {
                return this.messageSeatTimeCourseLaunchField;
            }
            set {
                this.messageSeatTimeCourseLaunchField = value;
            }
        }
        
        /// <remarks/>
        public string ActionToTakeUponIdleTimeOut {
            get {
                return this.actionToTakeUponIdleTimeOutField;
            }
            set {
                this.actionToTakeUponIdleTimeOutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.360training.com/")]
    public partial class ContentObject {
        
        private int contentObjectIDField;
        
        private int parentContentObjectIDField;
        
        private bool alowQuizTFField;
        
        private ContentObject[] contentObjectsField;
        
        private string nameField;
        
        private string contentObject_GUIDField;
        
        private int displayOrderField;
        
        /// <remarks/>
        public int ContentObjectID {
            get {
                return this.contentObjectIDField;
            }
            set {
                this.contentObjectIDField = value;
            }
        }
        
        /// <remarks/>
        public int ParentContentObjectID {
            get {
                return this.parentContentObjectIDField;
            }
            set {
                this.parentContentObjectIDField = value;
            }
        }
        
        /// <remarks/>
        public bool AlowQuizTF {
            get {
                return this.alowQuizTFField;
            }
            set {
                this.alowQuizTFField = value;
            }
        }
        
        /// <remarks/>
        public ContentObject[] ContentObjects {
            get {
                return this.contentObjectsField;
            }
            set {
                this.contentObjectsField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ContentObject_GUID {
            get {
                return this.contentObject_GUIDField;
            }
            set {
                this.contentObject_GUIDField = value;
            }
        }
        
        /// <remarks/>
        public int DisplayOrder {
            get {
                return this.displayOrderField;
            }
            set {
                this.displayOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.360training.com/")]
    public partial class TableOfContent {
        
        private ContentObject[] contentObjectsField;
        
        /// <remarks/>
        public ContentObject[] ContentObjects {
            get {
                return this.contentObjectsField;
            }
            set {
                this.contentObjectsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.360training.com/")]
    public partial class Asset {
        
        private int assetIDField;
        
        private string assetTypeField;
        
        private string uRLField;
        
        private string asset_GUIDField;
        
        private string assetSceneOrientationField;
        
        private string contentTextField;
        
        private bool isTopicTitleVisibleField;
        
        /// <remarks/>
        public int AssetID {
            get {
                return this.assetIDField;
            }
            set {
                this.assetIDField = value;
            }
        }
        
        /// <remarks/>
        public string AssetType {
            get {
                return this.assetTypeField;
            }
            set {
                this.assetTypeField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        public string Asset_GUID {
            get {
                return this.asset_GUIDField;
            }
            set {
                this.asset_GUIDField = value;
            }
        }
        
        /// <remarks/>
        public string AssetSceneOrientation {
            get {
                return this.assetSceneOrientationField;
            }
            set {
                this.assetSceneOrientationField = value;
            }
        }
        
        /// <remarks/>
        public string ContentText {
            get {
                return this.contentTextField;
            }
            set {
                this.contentTextField = value;
            }
        }
        
        /// <remarks/>
        public bool IsTopicTitleVisible {
            get {
                return this.isTopicTitleVisibleField;
            }
            set {
                this.isTopicTitleVisibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.360training.com/")]
    public partial class SequenceItem {
        
        private int sceneIDField;
        
        private bool isTitleVisibleField;
        
        private bool isTopicTitleVisibleField;
        
        private int sequenceItemIDField;
        
        private string item_GUIDField;
        
        private string sequenceItemTypeField;
        
        private int parentIDField;
        
        private Asset[] assetsField;
        
        private int sceneTemplateIDField;
        
        private string sceneGUIDField;
        
        private int sceneDurationField;
        
        private string contentObjectNameField;
        
        private bool isViewStreamingInSceneField;
        
        private string sceneNameField;
        
        private int sceneIDField1;
        
        private bool isTitleVisibleField1;
        
        private bool isTopicTitleVisibleField1;
        
        private bool isValidQuizField;
        
        private string videoFilenameField;
        
        private string streamingServerApplicationField;
        
        private int startQueueHoursField;
        
        private int startQueueMinutesField;
        
        private int startQueueSecondsField;
        
        private int endQueueHoursField;
        
        private int endQueueMinutesField;
        
        private int endQueueSecondsField;
        
        private int videoHeightField;
        
        private int videoWidthField;
        
        private bool fullScreenField;
        
        /// <remarks/>
        public int sceneID {
            get {
                return this.sceneIDField;
            }
            set {
                this.sceneIDField = value;
            }
        }
        
        /// <remarks/>
        public bool isTitleVisible {
            get {
                return this.isTitleVisibleField;
            }
            set {
                this.isTitleVisibleField = value;
            }
        }
        
        /// <remarks/>
        public bool isTopicTitleVisible {
            get {
                return this.isTopicTitleVisibleField;
            }
            set {
                this.isTopicTitleVisibleField = value;
            }
        }
        
        /// <remarks/>
        public int SequenceItemID {
            get {
                return this.sequenceItemIDField;
            }
            set {
                this.sequenceItemIDField = value;
            }
        }
        
        /// <remarks/>
        public string Item_GUID {
            get {
                return this.item_GUIDField;
            }
            set {
                this.item_GUIDField = value;
            }
        }
        
        /// <remarks/>
        public string SequenceItemType {
            get {
                return this.sequenceItemTypeField;
            }
            set {
                this.sequenceItemTypeField = value;
            }
        }
        
        /// <remarks/>
        public int ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
            }
        }
        
        /// <remarks/>
        public Asset[] Assets {
            get {
                return this.assetsField;
            }
            set {
                this.assetsField = value;
            }
        }
        
        /// <remarks/>
        public int SceneTemplateID {
            get {
                return this.sceneTemplateIDField;
            }
            set {
                this.sceneTemplateIDField = value;
            }
        }
        
        /// <remarks/>
        public string SceneGUID {
            get {
                return this.sceneGUIDField;
            }
            set {
                this.sceneGUIDField = value;
            }
        }
        
        /// <remarks/>
        public int SceneDuration {
            get {
                return this.sceneDurationField;
            }
            set {
                this.sceneDurationField = value;
            }
        }
        
        /// <remarks/>
        public string ContentObjectName {
            get {
                return this.contentObjectNameField;
            }
            set {
                this.contentObjectNameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsViewStreamingInScene {
            get {
                return this.isViewStreamingInSceneField;
            }
            set {
                this.isViewStreamingInSceneField = value;
            }
        }
        
        /// <remarks/>
        public string SceneName {
            get {
                return this.sceneNameField;
            }
            set {
                this.sceneNameField = value;
            }
        }
        
        /// <remarks/>
        public int SceneID {
            get {
                return this.sceneIDField1;
            }
            set {
                this.sceneIDField1 = value;
            }
        }
        
        /// <remarks/>
        public bool IsTitleVisible {
            get {
                return this.isTitleVisibleField1;
            }
            set {
                this.isTitleVisibleField1 = value;
            }
        }
        
        /// <remarks/>
        public bool IsTopicTitleVisible {
            get {
                return this.isTopicTitleVisibleField1;
            }
            set {
                this.isTopicTitleVisibleField1 = value;
            }
        }
        
        /// <remarks/>
        public bool IsValidQuiz {
            get {
                return this.isValidQuizField;
            }
            set {
                this.isValidQuizField = value;
            }
        }
        
        /// <remarks/>
        public string VideoFilename {
            get {
                return this.videoFilenameField;
            }
            set {
                this.videoFilenameField = value;
            }
        }
        
        /// <remarks/>
        public string StreamingServerApplication {
            get {
                return this.streamingServerApplicationField;
            }
            set {
                this.streamingServerApplicationField = value;
            }
        }
        
        /// <remarks/>
        public int StartQueueHours {
            get {
                return this.startQueueHoursField;
            }
            set {
                this.startQueueHoursField = value;
            }
        }
        
        /// <remarks/>
        public int StartQueueMinutes {
            get {
                return this.startQueueMinutesField;
            }
            set {
                this.startQueueMinutesField = value;
            }
        }
        
        /// <remarks/>
        public int StartQueueSeconds {
            get {
                return this.startQueueSecondsField;
            }
            set {
                this.startQueueSecondsField = value;
            }
        }
        
        /// <remarks/>
        public int EndQueueHours {
            get {
                return this.endQueueHoursField;
            }
            set {
                this.endQueueHoursField = value;
            }
        }
        
        /// <remarks/>
        public int EndQueueMinutes {
            get {
                return this.endQueueMinutesField;
            }
            set {
                this.endQueueMinutesField = value;
            }
        }
        
        /// <remarks/>
        public int EndQueueSeconds {
            get {
                return this.endQueueSecondsField;
            }
            set {
                this.endQueueSecondsField = value;
            }
        }
        
        /// <remarks/>
        public int VideoHeight {
            get {
                return this.videoHeightField;
            }
            set {
                this.videoHeightField = value;
            }
        }
        
        /// <remarks/>
        public int VideoWidth {
            get {
                return this.videoWidthField;
            }
            set {
                this.videoWidthField = value;
            }
        }
        
        /// <remarks/>
        public bool FullScreen {
            get {
                return this.fullScreenField;
            }
            set {
                this.fullScreenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.360training.com/")]
    public partial class Sequence {
        
        private SequenceItem[] sequenceItemsField;
        
        /// <remarks/>
        public SequenceItem[] SequenceItems {
            get {
                return this.sequenceItemsField;
            }
            set {
                this.sequenceItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void AddUpdateCacheCompletedEventHandler(object sender, AddUpdateCacheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUpdateCacheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUpdateCacheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void InvalidateCacheCompletedEventHandler(object sender, InvalidateCacheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InvalidateCacheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InvalidateCacheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void InvalidateCacheAndNotifyToAllRemainingServersCompletedEventHandler(object sender, InvalidateCacheAndNotifyToAllRemainingServersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InvalidateCacheAndNotifyToAllRemainingServersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InvalidateCacheAndNotifyToAllRemainingServersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591