//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.8009.
// 
#pragma warning disable 1591

namespace ICP4.CoursePlayer.CourseLevelRatingWeb {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CourseLevelRatingServiceBinding", Namespace="http://www.example.org/CourseLevelRatingService/")]
    public partial class CourseLevelRatingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NewOperationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CourseLevelRatingService() {
            this.Url = global::ICP4.CoursePlayer.Properties.Settings.Default.ICP4_CoursePlayer_CourseLevelRatingWeb_CourseLevelRatingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NewOperationCompletedEventHandler NewOperationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/ThreeSixtyTraining-CourseLevelRating/NewOperation", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CourseLevelRatingResponse", Namespace="http://www.example.org/CourseLevelRatingService")]
        public CourseLevelRatingResponse NewOperation([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.example.org/CourseLevelRatingService")] CLRRequestType CourseLevelRatingRequest) {
            object[] results = this.Invoke("NewOperation", new object[] {
                        CourseLevelRatingRequest});
            return ((CourseLevelRatingResponse)(results[0]));
        }
        
        /// <remarks/>
        public void NewOperationAsync(CLRRequestType CourseLevelRatingRequest) {
            this.NewOperationAsync(CourseLevelRatingRequest, null);
        }
        
        /// <remarks/>
        public void NewOperationAsync(CLRRequestType CourseLevelRatingRequest, object userState) {
            if ((this.NewOperationOperationCompleted == null)) {
                this.NewOperationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewOperationOperationCompleted);
            }
            this.InvokeAsync("NewOperation", new object[] {
                        CourseLevelRatingRequest}, this.NewOperationOperationCompleted, userState);
        }
        
        private void OnNewOperationOperationCompleted(object arg) {
            if ((this.NewOperationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewOperationCompleted(this, new NewOperationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.8009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/CourseLevelRatingService")]
    public partial class CLRRequestType {
        
        private string courseGuidField;
        
        private int ratingCountField;
        
        private double avgRatingField;
        
        /// <remarks/>
        public string courseGuid {
            get {
                return this.courseGuidField;
            }
            set {
                this.courseGuidField = value;
            }
        }
        
        /// <remarks/>
        public int ratingCount {
            get {
                return this.ratingCountField;
            }
            set {
                this.ratingCountField = value;
            }
        }
        
        /// <remarks/>
        public double avgRating {
            get {
                return this.avgRatingField;
            }
            set {
                this.avgRatingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.8009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.org/CourseLevelRatingService")]
    public partial class CourseLevelRatingResponse {
        
        private string successField;
        
        /// <remarks/>
        public string success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void NewOperationCompletedEventHandler(object sender, NewOperationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewOperationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewOperationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseLevelRatingResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseLevelRatingResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591