//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP4.CoursePlayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test.docusign.net/api/3.0/api.asmx")]
        public string ICP4_CoursePlayer_net_docusign_test_APIService {
            get {
                return ((string)(this["ICP4_CoursePlayer_net_docusign_test_APIService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://qa-ws1.austin.360training.com:443/webapp/wcs/services/CourseLevelRatingSe" +
            "rvice")]
        public string ICP4_CoursePlayer_CourseLevelRatingWeb_CourseLevelRatingService {
            get {
                return ((string)(this["ICP4_CoursePlayer_CourseLevelRatingWeb_CourseLevelRatingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.0.101.88/webapp/wcs/services/SuggestedCoursesDisplayService")]
        public string ICP4_CoursePlayer_SuggestedCoursesWeb_ThreeSixtyTraining_SuggestedCoursesDisplayService {
            get {
                return ((string)(this["ICP4_CoursePlayer_SuggestedCoursesWeb_ThreeSixtyTraining_SuggestedCoursesDisplayS" +
                    "ervice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.0.101.88:80/webapp/wcs/services/SuggestedCoursesDisplayService")]
        public string ICP4_CoursePlayer_SuggestedCourses_SuggestedCoursesDisplayService {
            get {
                return ((string)(this["ICP4_CoursePlayer_SuggestedCourses_SuggestedCoursesDisplayService"]));
            }
        }
    }
}
