//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4234
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4234.
// 
#pragma warning disable 1591

namespace ICP4.CoursePlayer.SuggestedCourses {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SCDServices", Namespace="http://www.example.org/SuggestedCoursesDisplayService/")]
    public partial class SuggestedCoursesDisplayService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSuggestedCoursesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SuggestedCoursesDisplayService() {
            this.Url = global::ICP4.CoursePlayer.Properties.Settings.Default.ICP4_CoursePlayer_SuggestedCourses_SuggestedCoursesDisplayService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSuggestedCoursesCompletedEventHandler GetSuggestedCoursesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/NewOperation", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SuggestedCoursesDisplayResponse", Namespace="http://www.example.org/SuggestedCoursesDisplayService")]
        public SuggestedCoursesDisplayResponseType GetSuggestedCourses([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.example.org/SuggestedCoursesDisplayService")] SuggestedCoursesDisplayRequest SuggestedCoursesDisplayRequest) {
            object[] results = this.Invoke("GetSuggestedCourses", new object[] {
                        SuggestedCoursesDisplayRequest});
            return ((SuggestedCoursesDisplayResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetSuggestedCoursesAsync(SuggestedCoursesDisplayRequest SuggestedCoursesDisplayRequest) {
            this.GetSuggestedCoursesAsync(SuggestedCoursesDisplayRequest, null);
        }
        
        /// <remarks/>
        public void GetSuggestedCoursesAsync(SuggestedCoursesDisplayRequest SuggestedCoursesDisplayRequest, object userState) {
            if ((this.GetSuggestedCoursesOperationCompleted == null)) {
                this.GetSuggestedCoursesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSuggestedCoursesOperationCompleted);
            }
            this.InvokeAsync("GetSuggestedCourses", new object[] {
                        SuggestedCoursesDisplayRequest}, this.GetSuggestedCoursesOperationCompleted, userState);
        }
        
        private void OnGetSuggestedCoursesOperationCompleted(object arg) {
            if ((this.GetSuggestedCoursesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSuggestedCoursesCompleted(this, new GetSuggestedCoursesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.org/SuggestedCoursesDisplayService")]
    public partial class SuggestedCoursesDisplayRequest {
        
        private SuggestedCoursesDisplayRequestType inField;
        
        /// <remarks/>
        public SuggestedCoursesDisplayRequestType @in {
            get {
                return this.inField;
            }
            set {
                this.inField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SuggestedCoursesDisplayService")]
    public partial class SuggestedCoursesDisplayRequestType {
        
        private string[] courseGuidsField;
        
        private string storeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("courseGuids")]
        public string[] courseGuids {
            get {
                return this.courseGuidsField;
            }
            set {
                this.courseGuidsField = value;
            }
        }
        
        /// <remarks/>
        public string storeId {
            get {
                return this.storeIdField;
            }
            set {
                this.storeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SuggestedCoursesDisplayService")]
    public partial class CourseInfo {
        
        private string courseGuidFromField;
        
        private string courseGuidToField;
        
        private string orderItemURLField;
        
        private string imageUrlField;
        
        /// <remarks/>
        public string courseGuidFrom {
            get {
                return this.courseGuidFromField;
            }
            set {
                this.courseGuidFromField = value;
            }
        }
        
        /// <remarks/>
        public string courseGuidTo {
            get {
                return this.courseGuidToField;
            }
            set {
                this.courseGuidToField = value;
            }
        }
        
        /// <remarks/>
        public string orderItemURL {
            get {
                return this.orderItemURLField;
            }
            set {
                this.orderItemURLField = value;
            }
        }
        
        /// <remarks/>
        public string imageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SuggestedCoursesDisplayService")]
    public partial class SuggestedCoursesDisplayResponseType {
        
        private CourseInfo[] courseListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Course", IsNullable=false)]
        public CourseInfo[] CourseList {
            get {
                return this.courseListField;
            }
            set {
                this.courseListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetSuggestedCoursesCompletedEventHandler(object sender, GetSuggestedCoursesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSuggestedCoursesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSuggestedCoursesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SuggestedCoursesDisplayResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SuggestedCoursesDisplayResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591